# Generated by Django 6.0.2 on 2026-02-23 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('location', models.CharField(blank=True, help_text='Area/Landmark', max_length=100)),
                ('telegram_id', models.CharField(blank=True, help_text='Telegram user ID for notifications', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('delivery_instructions', models.TextField(blank=True, help_text='Gate passcode, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['user__username'],
            },
        ),
    ]
