# Generated by Django 6.0.2 on 2026-02-23 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('packet_size', models.CharField(choices=[('half_litre', 'Half Litre (0.5L)'), ('one_litre', '1 Litre (1L)'), ('two_litre', '2 Litre (2L)')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_available', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='category.category')),
            ],
            options={
                'verbose_name': 'Milk Product',
                'verbose_name_plural': 'Milk Products',
                'ordering': ['category', 'packet_size'],
                'unique_together': {('category', 'packet_size')},
            },
        ),
    ]
