# Generated by Django 6.0.2 on 2026-02-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('cow_milk', 'Cow Milk'), ('buffalo_milk', 'Buffalo Milk'), ('ghee', 'Ghee')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of milk type')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Milk Category',
                'verbose_name_plural': 'Milk Categories',
                'ordering': ['name'],
            },
        ),
    ]
